- leancloud/file_.py
修复 hex-octet 生成随机数过程中的括号错位问题。参考 javascript-sdk: 
https://github.com/leancloud/javascript-sdk/blob/b61f967f53c3b88d3ef635712b67abdd6a70d521/lib/file.js#L519
> Fix off-by-one random generation typo

- leancloud/__init__.py
- leancloud/client.py
- tests/__init__.py
- tests/test_client.py
- tests/test_engine.py
- tests/test_object.py
- tests/test_query.py
- tests/test_user.py
增加了是否适用 master key 的选项。之前的 API，是根据 `leancloud.init` 的时候使用的 app key 还是 master key 来决定的。现在可以通过 API 来控制了。
新的 API 如果不调用，应该和以前的行为相同。
> add leancloud.use_master_key API

- leancloud/user.py
- tests/test_user.py
之前代码中有参考 JS SDK 调用了 _logout_with_all，这个方法是 JS SDK 在客户端的时候，登出的时候顺便把 Facebook 的 SDK 也登出掉。Python SDK 中没有类似设施，因此删除掉了。
> bugfix in User#logout

- leancloud/engine/leanengine.py
JS SDK 会把 App Info 通过 HTTP Payloads 发送过来，导致 Python 定义云函数没有接受额外参数的情况下会报错。
相关 ticket： https://ticket.leancloud.cn/tickets/8681
> pop cloud func params which starts with low dash

- leancloud/file_.py
The original hex_octet has probability 6% of generating
octet less-than-4 characters, which is not well-formed
to use in file key.
@see comments on #109.
> Fix: off-by-one random generation erro in hex_octet #109

- leancloud/query.py
查询时，order参数格式错了， 传了一个列表，导致多个列排序时，总是只有一个起作用。
通过和javascript sdk 对比，   才发现是python-sdk 里写错了。
> fix bug: Query是，排序参数order参数格式错误： 应该为以,分割的字符串，而不是一个列表

- leancloud/user.py
- tests/test_user.py
User#set 的时候会将原有 session token 覆盖掉，之前的单元测试没有覆盖到不使用 master key 的情况，没有发现。
> fix: don't set user._session_token to None when not set the session

- leancloud/engine/leanengine.py
Add a return statement that returns the original func instead of returning None.
> Fix engine.define decorator that made decorated function uncallable

- leancloud/__init__.py
- setup.py
怀疑在低版本 pip 下目前的 setup.py 中依赖 leancloud 会出现依赖问题，紧急发布一个版本改回以前的 setup.py 格式。
报错信息：
```
4/26/2016, 6:32:55 PM [ERROR] 部署失败：Requirement already satisfied (use --upgrade to upgrade): gevent>=1.0.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): gevent-websocket>=0.9.5 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Downloading/unpacking leancloud-sdk>=1.4.2 (from -r requirements.txt (line 3))
Downloading leancloud-sdk-1.4.2.tar.gz
Running setup.py (path:/tmp/pip_build_root/leancloud-sdk/setup.py) egg_info for package leancloud-sdk
Traceback (most recent call last):
File "<string>", line 17, in <module>
File "/tmp/pip_build_root/leancloud-sdk/setup.py", line 4, in <module>
import …
```
> fix: can't install in leanengine

- leancloud/object_.py
bug 的原因是，全局的 class 缓存，是按照 Python 的 class 的名字进行缓存的，没有使用使用者自定义的 `class_name` 名称进行缓存。
close: #311
> fix: invalid class cache if leancloud.Object's subclass has class_name

- leancloud/object_.py
Reverts leancloud/python-sdk#313
> Revert "fix: invalid class cache if leancloud.Object's subclass has class_name"

- setup.py
Via: http://docs.python-requests.org/en/master/community/faq/#what-are-hostname-doesn-t-match-errors
> feat: support SNI in earlier python versions (before 2.7.9)

- leancloud/cloudfunc.py
- tests/test_client.py
- tests/test_engine.py
之前放在了 leancloud.client 模块下，现在和其他 SDK 统一，放在 leancloud.cloudfunc 模块下。
> feat: add leancloud.cloudfunc.get_server_time

- setup.py
现在代码依赖 six 1.9.0 中增加的 `python_2_unicode_comaptible` 函数。
> :arrow_up: pin six module version

- Pipfile
- Pipfile.lock
- leancloud/engine/__init__.py
- setup.py
为云函数独立运行提供两个 API，并提供一个默认路由（接收健康检查）。
因为 start 方法需要启动 web 服务，所以我将 python-sdk 依赖了 `gevent = ">=1.0.2,<2.0.0"`，我不知道这样是否有很大的问题。
另外，我不确认我对 Pipfile 和 setup.py 的修改是否合适，而 Pipfile.lock 是 pipenv install 时候自动生成的。
最后，我不知道怎么针对这两个 API 写测试。。
修改后用户使用时大概是这样：
```
from gevent import monkey
monkey.patch_all() # NOQA
from leancloud import Engine
engine = Engine()
@engine.define
def hello(**params):
if 'name' in params:
return 'Hello, {}!'.format(params['name'])
else:
return 'What is your name?'
engine.start()
```
需要云引擎部署服务能够支持对于 Python 运行环境执行 `python app.py` 来启动应用。
@jysperm @ym @aisk @feisuzhu 帮忙看看。
> feat: add engine.start() and engine.stop() API

- leancloud/object_.py
- tests/test_object.py
- tests/test_query.py
Previously, the code checks whether the object has an truthy objectId,
to determine the existence of a LeanCloud object.
But if the object is constructed via `query.get("nonexist_objectId")`,
then it does have an objectId (`{"objectId": "nonexist_objectId"}`).
Therefore, we check whether the object has the `createdAt` attribute
instead.
> fix(LeanObject): test existence more accurately

- leancloud/file_.py
In _save_to_qiniu_internal_py3():
- remove unused import
- remove unused else cause of while True loop
> refactor(File): remove unused statements

- leancloud/engine/leanengine.py
- tests/test_engine.py
Previously updated_keys mistakenly attempt to get the value from
`__updateKeys` of request,
but actually the request sent by API uses `_updatedKeys`.
> fix(hooks): updated_keys

- leancloud/client.py
修正了云引擎预备环境错误触发生产环境 hook 的问题（之前 python-sdk 并不尊重运行实例的环境变量）。
为了保证向后兼容性（保证 `use_production` 可用），
所以仍然保留了使用全局变量控制 X-LC-Prod 头这样不太干净的方式。
相应地，也没有写新测试（因为 python 重新加载模块并不会更新对旧值的引用，使用 `del sys.modules` 这样 hacky 的方式会让测试很难看，也很容易造成其他测试的依赖问题）。
等以后 Python 发下一个大版本的时候再引入不用全局变量的方式。
> fix(LeanEngine): X-LC-Prod request header

- README.md
The package name has changed from leancloud-sdk
to leancloud long long ago.
Thanks to Tim Du for reporting this issue
(ticket: 20659)
> docs(readme): update outdated install info

- leancloud/object_.py
> fix a bug in _merge_metadata of object_.py

- leancloud/object_.py
- tests/test_object.py
This commit maintains compatibility with existing code
using the mistyped `deafult` parameter.
close #417
> fix: typo in get para: deafult -> default

- tests/test_file.py
Previously file_test requires there is already a specific existing user
in the application. This commit removes this requirement.
see also #439
> test: make file_test stateless

- leancloud/__init__.py
- leancloud/cloudfunc.py
cloudfunc has been renamed to cloud since 2.1.0
see also leancloud/docs#3636
> refactor: remove unused cloudfunc module

- leancloud/cloud.py
- tests/test_engine.py
Previously E.164 format is not supported
(but you can specify the region with an additional idd parameter).
Now both numbers with or without a leading `+` are supported.
If there are region inconsistence between phone_number and idd,
phone_number takes priority.
> feat(sms): phone_number para of request_sms_code supports E.164 format

- .github/workflows/pythonpackage.yml
- .github/workflows/pythonpublish.yml
- README.md
- requirements.txt
- setup.py
Since pip install wheels will not execute arbitrary code,
we need to specify the conditional dependencies statically.
related ticket: 37431
Other changes:
- Only support Python 2.7.18 for Python 2.
- Use ubuntu 20.04 for github actions.
> fix: conditional dependencies for Python 2

- leancloud/client.py
`Object.disable_after_hook()` won't work unless `LC-Hook-Key` header is set.
> Add hook key header

- leancloud/engine/leanengine.py
- tests/test_engine.py
The key LeanEngine received is not `object` but `authData`.
Thank @cshuaimin for bringing this to our attention.
> fix: on_auth_data hook

- leancloud/client.py
LC_API_SERVER 已经被 LEANCLOUD_API_SERVER 所代替，优先选择 LEANCLOUD_ 开头的环境变量。
> Prefer LEANCLOUD_* envs to LC_* ones

- .github/workflows/pythonpackage.yml
- leancloud/user.py
- requirements.txt
- setup.py
- tests/test_engine.py
- tests/test_user.py
> fix: require phone_number when verify sms code

- changelog
- setup.py
从 3.0.0 开始，将不再支持 python 2.7 和 3.5 。
> release: 3.0

- Pipfile
- leancloud/client.py
- requirements.txt
- setup.py
Enable TCP keepalive socket option when requesting to storage.
Fix "ConnectionResetError: [Errno 104] Connection reset by peer"
ticket #41769
https://github.com/psf/requests/issues/4664
https://codearcana.com/posts/2015/08/28/tcp-keepalive-is-a-lie.html
https://blog.cloudflare.com/when-tcp-sockets-refuse-to-die
> fix connection reset error
