leancloud/python-sdk

- leancloud/client.py
- setup.py
fix https://github.com/leancloud/python-sdk/issues/19
> support requests-2.2-support

- leancloud/errors.py
fix https://github.com/leancloud/python-sdk/issues/23
> unicode error support

- leancloud/client.py
- leancloud/user.py
- tests/test_user.py
if user logined, set session token in request headers
> fix session token

- leancloud/user.py
gevent.local.local 和 threading.local 行为不太一致
> fix gevent.local.local

- leancloud/__init__.py
- leancloud/client.py
- tests/test_client.py
- tests/test_user.py
> add use_production

- leancloud/object_.py
fix https://github.com/leancloud/python-sdk/issues/60
> fix Role class don't have underscore prefix

- leancloud/client.py
request-sign 的方式在使用 master key 的时候会失效，暂时绕过。
> use Master-Key in request header if use master key

- .travis.yml
- leancloud/client.py
- tests/__init__.py
- tests/test_client.py
- tests/test_object.py
- tests/test_query.py
1. add enviromental variable  travis_timeout 
2. add get_server_time method
> Travis timeout

- leancloud/engine/authorization.py
https://github.com/leancloud/python-sdk/issues/98
> bugfix in leanengine master key auth

- leancloud/object_.py
- tests/test_engine.py
相关 bug: https://forum.leancloud.cn/t/python-save/3748
> decode engine.current_user to leancloud.User object

- leancloud/file_.py
Reverts leancloud/python-sdk#109
> Revert "Fix off-by-one random generation typo"

- leancloud/__init__.py
- leancloud/client.py
- tests/test_client.py
- tests/test_user.py
> 重构 client.py

- leancloud/engine/leanengine.py
- tests/test_engine.py
- tests/test_user.py
之前 hook 函数都忽略了 body 中的 user 参数，导致拿不到当前用户，现在修正此问题。
> bugfix in engine hook current user

- leancloud/object_.py
- tests/test_object.py
close https://github.com/leancloud/python-sdk/issues/129
> feat: add Object.save_all and Object.destroy_all

- .travis.yml
- leancloud/__init__.py
- leancloud/errors.py
- leancloud/object_.py
- leancloud/query.py
- leancloud/user.py
- leancloud/utils.py
- tests/test_object.py
- tests/test_query.py
- tests/test_user.py
> make leancloud.Object.attributes readonly

- .travis.yml
- leancloud/object_.py
- tests/test_query.py
增加了 leancloud.Object.query 方法，方便快速构造 Query 对象（之前需要 leancloud.Query('class_name')）。
@juvenn @dittoyi
> Object query

- .travis.yml
- leancloud/role.py
- tests/test_role.py
close: https://github.com/leancloud/python-sdk/issues/144
> Query role

- leancloud/object_.py
- leancloud/user.py
- tests/test_file.py
- tests/test_object.py
close: https://github.com/leancloud/python-sdk/issues/135
> add Object.fetch_when_save flag

- leancloud/client.py
- leancloud/engine/leanengine.py
- leancloud/engine/utils.py
- leancloud/object_.py
- leancloud/utils.py
- tests/test_engine.py
- tests/test_util.py
API Added:
- leancloud.Object.disable_before_hook
- leancloud.Object.disable_after_hook
Close #133
> implement disable hook

- changelog
close https://github.com/leancloud/python-sdk/issues/151
> docs: fix the publish date typo in changelog

- leancloud/object_.py
- tests/test_object.py
close https://github.com/leancloud/python-sdk/issues/136
> feat: allow where param in leancloud.Object.save

- .travis.yml
- dev-requirements.txt
- setup.py
next time when we bump the version number, just edit the version num in the `leancloud/__init__.py`.
> Import the version in the setup.py

- leancloud/query.py
- leancloud/relation.py
- tests/test_relation.py
close: https://github.com/leancloud/python-sdk/issues/159
> feat: change Relation.query to a property

- .travis.yml
- dev-requirements.txt
- leancloud/_compat.py
- leancloud/acl.py
- leancloud/client.py
- leancloud/engine/authorization.py
- leancloud/engine/cloudfunc.py
- leancloud/engine/leanengine.py
- leancloud/engine/utils.py
- leancloud/file_.py
- leancloud/object_.py
- leancloud/push.py
- leancloud/query.py
- leancloud/role.py
- leancloud/user.py
- leancloud/utils.py
- setup.py
- tests/request_generator.py
- tests/test_engine.py
- tests/test_file.py
- tests/test_object.py
- tests/test_query.py
- tests/test_user.py
This PR is related to #43.
Note that only tests are fine and we still need carefully review on it before merge it to master.
Let me know if you have any concerns.
> Python3 support

- .travis.yml
* make sure we can get the code coverage report;
* fix trailing space;
* simplify the way to install the packages;
Nose doc for code coverage:
-  http://nose.readthedocs.org/en/latest/plugins/cover.html
---
It seems that we don't have any code coverage report yet _(:3
> Clean up the travis configuration file

- .travis.yml
- leancloud/client.py
- leancloud/engine/cloudfunc.py
- leancloud/file_.py
- leancloud/object_.py
- leancloud/push.py
- leancloud/query.py
- leancloud/user.py
- leancloud/utils.py
- tests/test_engine.py
- tests/test_push.py
- tests/test_user.py
since we dropped the support for 2.6 in the PR #137
> Remove the hack for python 2.6

- leancloud/engine/cors.py
https://github.com/leancloud/cloud-code/issues/753
> feat: support `X-LC-UA` CORS header

- .travis.yml
- leancloud/file_.py
- leancloud/object_.py
- tests/sample_text.txt
- tests/test_file.py
- tests/test_file.txt
Also add checksum to file metadata
> Upload file via fileToken

- leancloud/engine/authorization.py
- leancloud/engine/leanengine.py
- leancloud/engine/utils.py
- leancloud/object_.py
- leancloud/utils.py
- tests/test_engine.py
- tests/test_user.py
- tests/test_util.py
ref: https://github.com/leancloud/leanengine-node-sdk/pull/73
@jysperm
> refactor: hook sign

- leancloud/object_.py
- tests/test_query.py
> feat: allow Object.get method get objectId / createAt/ updatedAt field

- leancloud/user.py
- stubs/leancloud/user.pyi
- tests/test_user.py
> feat: add leancloud.User#get_roles()

- leancloud/engine/__init__.py
> feat: rename leancloud.Engine#on_bigquery to leancloud.Engine#on_insight

- leancloud/push.py
- tests/test_push.py
> fix: leancloud.push.Notification unsupported fetch data from server

- leancloud/user.py
- tests/test_user.py
> feat: add User#refresh_session_token()

- leancloud/user.py
- tests/test_user.py
> feat: add User#is_authenticated()

- dev-requirements.txt
- leancloud/engine/cookie_session.py
- leancloud/user.py
- setup.py
- tests/test_middlewares.py
> feat: clear CookieSessionMiddleware's cookie while leancloud.User#logout

- tests/test_object.py
> test: add create_without_data test

- leancloud/query.py
- tests/test_query.py
> feat: support leancloud.Query#scan

- leancloud/file_.py
- leancloud/query.py
- leancloud/utils.py
- tests/test_file.py
> feat: support query on leancloud.File

- leancloud/file_.py
- tests/test_file.py
https://github.com/leancloud/uluru-platform/issues/3201
> feat: implement file callback

- leancloud/query.py
- tests/test_query.py
close: https://github.com/leancloud/python-sdk/issues/256
> feat: add Query#size_equal_to

- leancloud/object_.py
- tests/test_object.py
> :bug: fix invalid timezone on fetched leancloud.Object#created_at and leancloud.Object#updated_at

- .gitignore
- leancloud/engine/https_redirect_middleware.py
request.query_string is a byte, so I convert it to unicode in Py3.
> fix HttpsRedirectMiddleware bug in issues #303

- .travis.yml
- leancloud/engine/__init__.py
- leancloud/engine/leanengine.py
- tests/test_engine.py
> feat: add fetch_user option in leancloud.Engine constructor

- leancloud/object_.py
- leancloud/operation.py
- tests/test_object.py
- tests/test_op.py
https://github.com/leancloud/paas/issues/811
> :sparkles: add bit operation

- leancloud/__init__.py
- leancloud/conversation.py
- leancloud/object_.py
- leancloud/sys_message.py
- tests/test_sys_message.py
封装了基本的 https://leancloud.cn/docs/realtime_v2.html#_SysMessage 类型。
> :sparkles: add leancloud.SysMessage

- leancloud/query.py
对应 JS SDK 中的 AV.Query#_createRequest
> :hammer: add leancloud.Query#_do_request hook

- leancloud/__init__.py
- leancloud/status.py
- leancloud/user.py
- tests/test_status.py
> add leancloud.Status

- leancloud/cloud.py
> fix cloud request_sms_code

- Pipfile.lock
- changelog
- leancloud/__init__.py
- leancloud/engine/cookie_session.py
- setup.py
- Fixed CookieSessionMiddleware.pre_process fail when session_token doesn't exist in Cookies
- Fixed unit test for AVFile
- LeanCloud API App Router v2 for us-w1 and cn-e1
> Release 2.1.9

- Pipfile
- Pipfile.lock
security update for CVE-2019-11324
close #398
> fix: update requests dependency to 2.22.0

- setup.py
> fix: typo in requires list of setup.py

- leancloud/engine/authorization.py
https://github.com/leancloud/rfcs/issues/1043
> support androidx key

- leancloud/push.py
- tests/test_push.py
> feat(push): support flow_control

- tests/test_conversation.py
Now rtm will sort members when saving `m`.
> test: members may be sorted

- Pipfile
- README.md
- setup.py
- tests/test_user.py
related forum post: 22216, 22168, 22182
related ticket: 23058
> fix: require Werkzeug <1.0.0

- leancloud/push.py
- tests/test_push.py
> feat(push): add prod parameter

- tests/test_query.py
> test includeACL

- README.md
- leancloud/__init__.py
- leancloud/engine/leanengine.py
- leancloud/query.py
- leancloud/role.py
- tests/test_engine.py
- fix(engine): LeanEngineError status
- fix(engine): typo
- test(engine): update test_lean_engine_error
- docs: how to run single test
- style: automatically formatted by black
> engine error

- .vscode/settings.json
- README.md
- tests/test_push.py
- tests/test_user.py
- test: fix test_basic_push
- doc: refine single test running
> fix push test

- .travis.yml
> test: test against python 3.9

- leancloud/file_.py
- tests/test_file.py
and allow users to specify file key with master key
> refactor: simplify code according to api updates

- README.md
- requirements.txt
- setup.py
> feat: support  python 3.9, drop python 3.5

- leancloud/file_.py
- requirements.txt
- setup.py
> fix: update qiniu dependency

- leancloud/engine/__init__.py
- leancloud/engine/leanengine.py
- tests/test_engine.py
stolen from leancloud/leanengine-node-sdk#163
> feat: on_auth_data hook

- leancloud/file_.py
- tests/test_file.py
see also leancloud/javascript-sdk#640
> fix: hide url attribute when file upload failed
